#21 1.Rate limit for authenticated user and anonymous user
jknaresh/django_generic_api pull request #26
Opened 2024-10-28 21:02 UTC by ShrijanL

- Initiated rate limiting by DRF throttling for authenticated and anonymous user.
- Raises 429 error if predefined limit exceeds

2024-10-29 18:21 UTC, nareshelequin requested changes
update required changes.

2024-10-29 18:21 UTC, nareshelequin commented on django_generic_api/__init__.py
> +# django_generic_api/__init__.py
missing documentation.

2024-10-29 18:21 UTC, nareshelequin commented on django_generic_api/utils.py
> +def timeparse(period):
`time_parse`, instead timeparse

2024-10-29 18:21 UTC, nareshelequin commented on django_generic_api/views.py
> +    throttle_classes = [UserRateThrottle]
try with using throttle_classes and should be same behavior.

2024-10-30 12:45 UTC, ShrijanL commented on django_generic_api/__init__.py
> +# django_generic_api/__init__.py
updated documentation

2024-10-30 12:46 UTC, ShrijanL commented on django_generic_api/views.py
> +    throttle_classes = [UserRateThrottle]
removed throttles at class based views

2024-10-30 18:47 UTC, nareshelequin requested changes
required review changes.

2024-10-30 18:47 UTC, nareshelequin commented on django_generic_api/utils.py
> +                "error": "Too many requests. Please wait for sometime.",
update message with,
Too many requests. Please try after sometime.

2024-10-30 18:47 UTC, nareshelequin commented on django_generic_api/utils.py
> +                "code": "DGA-U003",
update error code with error code documentation.

2024-10-30 19:39 UTC, ShrijanL commented on django_generic_api/utils.py
> +                "error": "Too many requests. Please wait for sometime.",
changed error message

2024-10-30 19:39 UTC, ShrijanL commented on django_generic_api/utils.py
> +                "code": "DGA-U003",
updated in errorcode.md

2024-10-30 19:44 UTC, nareshelequin approved these changes

2024-10-30 19:45 UTC, merged