Email validation
jknaresh/django_generic_api pull request #29
Opened 2024-10-30 18:39 UTC by ShrijanL

- Email validation has been completed.
- A text file containing a set of valid email domains has been created.

2024-10-30 20:17 UTC, nareshelequin requested changes

2024-11-01 20:28 UTC, nareshelequin requested changes

2024-11-01 20:28 UTC, nareshelequin commented on django_generic_api/views.py
>          email = validate_register_data.email
Email string validation? 
what will happen, if input is not an email?

2024-11-01 20:35 UTC, nareshelequin approved these changes

2024-11-01 20:40 UTC, ShrijanL commented on django_generic_api/views.py
>          email = validate_register_data.email
configured email as emailstr in pydantic level.

2024-11-01 20:41 UTC, merged