Default value in saveInput
jknaresh/django_generic_api pull request #36
Opened 2024-11-03 13:17 UTC by ShrijanL

- if null=false, default value is given, user value is given, takes user value
- if null=false, default value is given, user value is not given, takes user value

2024-11-03 18:27 UTC, jknaresh requested changes
think and optimise

2024-11-03 18:27 UTC, jknaresh commented on django_generic_api/services.py
>              if is_optional:
i think we have to reverse this process, like

is_optional = field1.null or field1.blank ur field1.has_default()

if it has default value, and input empty or null. model will update with default value. or any other idea?

2024-11-05 14:32 UTC, ShrijanL commented on django_generic_api/services.py
>              if is_optional:
takes default value if null=false and input value is set as null.

2024-11-06 21:27 UTC, nareshelequin requested changes

2024-11-06 21:27 UTC, nareshelequin commented on django_generic_api/services.py
> +        if django_field_name in DJANGO_TO_PYDANTIC_TYPE_MAP:
What if django field not found in map dict?
Use `dict.get` instead `in` while checking.

2024-11-06 21:27 UTC, nareshelequin commented on django_generic_api/services.py
> +            # Apply constraints such as `max_length` if they exist for the field
Apply constraints such as `max_length` if they exist for the field???
Seems assignment to pydontic model field?

2024-11-06 21:27 UTC, nareshelequin commented on django_generic_api/services.py
> +        for field_name, value in list(saveInput.items()):
For field_name, value in list(saveInput.items()): ??? 

list of dict.items()?

use directly, dict.items()?

2024-11-06 21:27 UTC, nareshelequin commented on django_generic_api/services.py
> +                model_field.get_prep_value(value)
FYI, apply same behavior with fetch filter?

2024-11-07 14:19 UTC, ShrijanL commented on django_generic_api/services.py
> +        if django_field_name in DJANGO_TO_PYDANTIC_TYPE_MAP:
raise error if django field not found in map dict,
used .get to get value from dict.

2024-11-07 14:20 UTC, ShrijanL commented on django_generic_api/services.py
> +            # Apply constraints such as `max_length` if they exist for the field
Changed comment as assigning attribute 'max length' if they exist for field.

2024-11-07 14:39 UTC, ShrijanL commented on django_generic_api/services.py
> +                model_field.get_prep_value(value)
Created a ticket for this.
https://github.com/jknaresh/django_generic_api/issues/40

2024-11-07 14:39 UTC, ShrijanL commented on django_generic_api/services.py
> +        for field_name, value in list(saveInput.items()):
as the dictionary changes its size due to default value while iterating over the dict, it throws a runtime error,
so i converted it to list.

2024-11-12 20:37 UTC, nareshelequin approved these changes

2024-11-12 20:54 UTC, merged