Error code formatting
jknaresh/django_generic_api pull request #39
Opened 2024-11-06 17:55 UTC by ShrijanL

- Created custom exception class.
- Formatted ERRORCODES.md file.
- Used CustomAPIError class to raises and catches the errors.

2024-11-06 21:46 UTC, nareshelequin requested changes

2024-11-06 21:46 UTC, nareshelequin commented on django_generic_api/services.py
> +        "Model not found", "DGA-S001", status.HTTP_404_NOT_FOUND
Use, kwargs instead args.

2024-11-06 21:46 UTC, nareshelequin commented on django_generic_api/utils.py
>              except FieldDoesNotExist:
How do you handle? if something else exception raised?

2024-11-06 21:46 UTC, nareshelequin commented on django_generic_api/views.py
> +            custom_error = CustomAPIError(
Seems `CustomAPIError` class is not used as expected way. Try using expected way.

2024-11-07 15:12 UTC, ShrijanL commented on django_generic_api/utils.py
>              except FieldDoesNotExist:
Added Execption case.

2024-11-12 22:07 UTC, ShrijanL commented
will work later on this issue
#38

2024-11-12 22:07 UTC, closed without merging