Fetch filter update
jknaresh/django_generic_api pull request #41
Opened 2024-11-07 23:28 UTC by ShrijanL

- Used get_prep_value() in fetch filter validation.
- Removed validation_func mapping dict.

2024-11-08 12:49 UTC, nareshelequin requested changes

2024-11-08 20:06 UTC, nareshelequin requested changes

2024-11-08 20:06 UTC, nareshelequin commented on django_generic_api/utils.py
> +    field_properties = {
based on field type, make field properties.
ex: max_length do not have datetime field ... etc

2024-11-08 21:15 UTC, ShrijanL commented on django_generic_api/services.py
> +    model_fields = get_model_fields_with_properties(model, field1)
converted to [field1]

2024-11-08 21:15 UTC, ShrijanL commented on django_generic_api/services.py
> +            is_valid_value *= False
done.

2024-11-08 21:18 UTC, ShrijanL commented on django_generic_api/utils.py
> +    field_properties = {
updated as 
checks if it has maxlength then gets it, else None

2024-11-08 21:41 UTC, ShrijanL commented on django_generic_api/utils.py
> +    if field_list:
1. for len(field_list) > 1, ,
from filter.names , pop id and timestamp values and if len >1 , throw error

2. As the filter.names are already validated before hand, no need to validate again.

2024-11-09 01:22 UTC, ShrijanL commented on django_generic_api/utils.py
> +    if field_list:
1. According to the payload model, filter.name accepts only a single string value and does not allow multiple values, so there is no need to check the length of filter.name.
If filter.name is set to id, inserted_timestamp, update_timestamp, or end_timestamp, an error will be raised indicating that the field is not permitted for filtering.

2024-11-12 21:16 UTC, ShrijanL commented on django_generic_api/services.py
> +        UNCOUNTABLE_FIELDS = [
removed this part.

2024-11-12 21:33 UTC, ShrijanL commented on django_generic_api/utils.py
> +        "max_length": (
updated

2024-11-12 22:05 UTC, nareshelequin approved these changes

2024-11-12 22:08 UTC, merged