Test cases for each API
jknaresh/django_generic_api pull request #53
Opened 2024-11-17 20:33 UTC by ShrijanL

- Created test separate file for each API with parameterization.

2024-11-19 14:52 UTC, nareshelequin requested changes

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_wrong_payload_format(
test_invalid_payload_format

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_invalid_fetch_filter_name_field(
repeated test case.

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_invalid_fetch_filter_value_datatype(
test_invalid_fetch_filter_value_element_datatype

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_multiple_filter_eq_operator(
test_invalid_filter_value_length_for_eq_operator

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_pagesize_is_not_int(
test_unknown_page_number

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_sort_not_dictionary(
test_unknow_format_sort_property

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_missing_authentication_header(self, fetch_data_1, api_client):
repeated test case.

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_incorrect_token_format(
repeated test case.

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +        self, fetch_data_1, api_client, add_perm_token
repeated test case.

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_fetch.py
> +    def test_positive_fetch_scenario(
test_fetch_single_filter

2024-11-19 14:52 UTC, nareshelequin commented on django_generic_api/tests/test_login.py
> +    def test_missing_field_in_payload(self, api_client):
test_missing_username_property

2024-11-19 15:20 UTC, ShrijanL commented on django_generic_api/tests/test_activate.py
> +        token = f"{email_activate_inactive_user_id}:{timestamp}"
encoded the token using base64 to not reveal the information in token.

2024-11-19 15:21 UTC, ShrijanL commented on django_generic_api/tests/test_activate.py
Changed file name to test_activate_email.py

2024-11-19 15:43 UTC, ShrijanL commented on django_generic_api/tests/test_activate.py
> +        User.objects.filter(id=user_id).delete()  # Simulate user deletion
removed as passed a non existing user.

2024-11-19 15:45 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_missing_required_field(
renamed.

2024-11-19 15:46 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_wrong_token_format(self, api_client, view_perm_token):
renamed.

2024-11-19 15:46 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_fetch_perm_user(self, fetch_data_1, api_client, view_perm_token):
renamed.

2024-11-19 15:47 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_wrong_payload_format(
renamed.

2024-11-19 15:49 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_modelName_not_str(
renamed,

2024-11-19 15:50 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_wrong_fields_datatype(
renamed,

2024-11-19 15:52 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_invalid_fetch_filter_name_field(
removed test case.

2024-11-19 15:52 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_invalid_fetch_filter_value_datatype(
renamed.

2024-11-19 15:54 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_pagesize_is_not_int(
renamed.

2024-11-19 15:55 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_sort_not_dictionary(
renamed.

2024-11-19 15:55 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_missing_authentication_header(self, fetch_data_1, api_client):
removed test case.

2024-11-19 15:56 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +        self, fetch_data_1, api_client, add_perm_token
removed test case.

2024-11-19 15:56 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_incorrect_token_format(
removed test case,

2024-11-19 15:57 UTC, ShrijanL commented on django_generic_api/tests/test_fetch.py
> +    def test_positive_fetch_scenario(
renamed.

2024-11-19 16:10 UTC, ShrijanL commented on django_generic_api/tests/test_login.py
> +    def test_missing_field_in_payload(self, api_client):
renamed.

2024-11-20 21:23 UTC, nareshelequin requested changes

2024-11-20 21:23 UTC, nareshelequin commented on django_generic_api/apps.py
> +                "anon": "25/hour",  # Rate limit for unauthenticated users,
should be configurable, as per USER request.

2024-11-20 21:24 UTC, ShrijanL commented on django_generic_api/apps.py
> +                "anon": "25/hour",  # Rate limit for unauthenticated users,
created ticket for this issue.
https://github.com/jknaresh/django_generic_api/issues/30

2024-11-20 21:35 UTC, nareshelequin approved these changes

2024-11-20 21:36 UTC, merged