Forgot password API
jknaresh/django_generic_api pull request #62
Opened 2024-12-02 19:30 UTC by ShrijanL

- Implemented Forgot Password API with integration to the New Password API.
- Integrated Captcha service for Forgot Password and Sign-Up workflows.
- Developed and validated test cases for Forgot Password, New Password, and Captcha service APIs.

2024-12-06 22:02 UTC, nareshelequin requested changes

2024-12-08 20:40 UTC, ShrijanL commented on django_generic_api/tests/test_captcha.py
> +    def test_captcha_post_success(self, api_client):
added 2 negative testcases.

2024-12-09 18:41 UTC, ShrijanL commented on django_generic_api/apps.py
> +        DEFAULT_CACHE_SETTINGS = {
3. Updated such that if user defines cache with `default ` as key , it raises error

2024-12-12 16:21 UTC, nareshelequin commented on README.md
> +            "captcha_number": <captcha_number>
rename to captcha_value.

2024-12-12 16:24 UTC, nareshelequin commented on django_generic_api/apps.py
>              if key not in settings.REST_FRAMEWORK:
if key not in settings.REST_FRAMEWORK:
update to `if not settings.REST_FRAMEWORK.get(key):`

2024-12-12 16:25 UTC, nareshelequin commented on django_generic_api/apps.py
> +            if "default" not in settings.CACHES:
update to `if not settings.CACHES.get("default"):`

2024-12-12 16:28 UTC, nareshelequin commented on django_generic_api/payload_models.py
> +    captcha_number: int
update to `captcha_value`. and find is there any python captcha default captcha format is there? if yes, user can define? try define with alpha numeric and test.

2024-12-12 16:35 UTC, nareshelequin commented on django_generic_api/views.py
> +        image_captcha = ImageCaptcha()
Develop HTML and share screenshot? how it's looking with required place?

2024-12-13 18:42 UTC, ShrijanL commented on README.md
> +            "captcha_number": <captcha_number>
done

2024-12-13 18:42 UTC, ShrijanL commented on django_generic_api/apps.py
>              if key not in settings.REST_FRAMEWORK:
done

2024-12-13 18:47 UTC, ShrijanL commented on django_generic_api/views.py
> +        image_captcha = ImageCaptcha()
![captcha_example](https://github.com/user-attachments/assets/f2150f7c-a712-4a4f-ae04-ec7d886207e1)

2024-12-17 16:14 UTC, ShrijanL commented on django_generic_api/apps.py
> +            if "default" not in settings.CACHES:
Removed cache as it is not used

2024-12-17 16:14 UTC, ShrijanL commented on django_generic_api/payload_models.py
> +    captcha_number: int
updated with captcha_value

2024-12-19 17:24 UTC, nareshelequin approved these changes

2024-12-19 17:31 UTC, merged